"""
Home renovation module API endpoints.
CRUD for rooms, tasks, and ideas.

Every write goes through `_require_editor`, so a user who may only look at the
module (see services/access.py) cannot change data by calling the API directly.
"""
from __future__ import annotations

import re
import sqlite3
from pathlib import Path
from typing import Any, Optional

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile
from fastapi.responses import FileResponse
from pydantic import BaseModel, field_validator

from ..db import get_db_conn
from ..services.access import can_edit_renovation, normalise_username
from ..services.uploads import UploadRejected, random_stored_name, validate_image

router = APIRouter(prefix="/api/renovation", tags=["renovation"])

TASK_STATUSES = ("todo", "in_progress", "done")
TASK_PRIORITIES = ("low", "medium", "high")
IDEA_STATUSES = ("new", "considering", "approved", "rejected")
IDEA_COLORS = ("white", "amber", "orange", "green", "teal", "blue", "purple", "pink")
SUPPLY_STATUSES = ("needed", "bought")

# Journal photos live outside the database: app/uploads/renovation_journal/
JOURNAL_PHOTOS_DIR = Path(__file__).resolve().parents[3] / "uploads" / "renovation_journal"
JOURNAL_SLOTS = {"before": "before_photo", "after": "after_photo"}
JOURNAL_MAX_PHOTO_MB = 12

# Stored names are generated by random_stored_name(), so anything else in a
# photo URL is a probe rather than one of our files.
_STORED_NAME_RE = re.compile(r"^[0-9a-f]{32}\.(jpg|jpeg|png|gif|webp)$")


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _current_user(request: Request) -> Any:
    user = getattr(request.state, "user", None)
    if user:
        return user
    try:
        return request.session.get("user")
    except Exception:
        return None


def _require_editor(request: Request) -> str:
    """Abort with 403 unless the caller may modify renovation data."""
    user = _current_user(request)
    if not can_edit_renovation(user):
        raise HTTPException(status_code=403, detail="אין לך הרשאה לערוך את נתוני השיפוץ")
    return normalise_username(user)


def _clean(value: Optional[str]) -> Optional[str]:
    """Trim a free-text field, turning blanks into NULL."""
    if value is None:
        return None
    trimmed = value.strip()
    return trimmed or None


def _one_of(field: str, allowed: tuple[str, ...]):
    """Reusable pydantic validator that keeps enum-ish columns clean."""
    def _check(cls, v):  # noqa: N805 - pydantic validator signature
        if v is None:
            return v
        if v not in allowed:
            raise ValueError(f"{field} must be one of {allowed}")
        return v
    return _check


def _room_exists(db_conn: sqlite3.Connection, room_id: Optional[int]) -> None:
    if room_id is None:
        return
    row = db_conn.execute("SELECT 1 FROM renovation_rooms WHERE id=?", (room_id,)).fetchone()
    if not row:
        raise HTTPException(status_code=400, detail="החדר שנבחר לא קיים")


def _task_exists(db_conn: sqlite3.Connection, task_id: Optional[int]) -> None:
    if task_id is None:
        return
    row = db_conn.execute("SELECT 1 FROM renovation_tasks WHERE id=?", (task_id,)).fetchone()
    if not row:
        raise HTTPException(status_code=400, detail="המשימה שנבחרה לא קיימת")


def _apply_updates(
    db_conn: sqlite3.Connection,
    table: str,
    row_id: int,
    updates: dict,
    not_found: str,
) -> dict:
    existing = db_conn.execute(f"SELECT * FROM {table} WHERE id=?", (row_id,)).fetchone()
    if not existing:
        raise HTTPException(status_code=404, detail=not_found)
    if not updates:
        return dict(existing)
    set_clause = ", ".join(f"{k}=?" for k in updates)
    db_conn.execute(
        f"UPDATE {table} SET {set_clause}, updated_at=CURRENT_TIMESTAMP WHERE id=?",
        (*updates.values(), row_id),
    )
    db_conn.commit()
    return dict(db_conn.execute(f"SELECT * FROM {table} WHERE id=?", (row_id,)).fetchone())


# ─── Schemas ─────────────────────────────────────────────────────────────────

class RoomCreate(BaseModel):
    name: str
    icon: str = "🏠"
    notes: Optional[str] = None
    image_url: Optional[str] = None
    sort_order: int = 0

    @field_validator("name")
    @classmethod
    def _name_not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("name is required")
        return v.strip()


class RoomUpdate(BaseModel):
    name: Optional[str] = None
    icon: Optional[str] = None
    notes: Optional[str] = None
    image_url: Optional[str] = None
    sort_order: Optional[int] = None


class TaskCreate(BaseModel):
    title: str
    room_id: Optional[int] = None
    status: str = "todo"
    priority: str = "medium"
    due_date: Optional[str] = None
    notes: Optional[str] = None
    link_url: Optional[str] = None

    @field_validator("title")
    @classmethod
    def _title_not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("title is required")
        return v.strip()

    _status_ok = field_validator("status")(_one_of("status", TASK_STATUSES))
    _priority_ok = field_validator("priority")(_one_of("priority", TASK_PRIORITIES))


class TaskUpdate(BaseModel):
    title: Optional[str] = None
    room_id: Optional[int] = None
    status: Optional[str] = None
    priority: Optional[str] = None
    due_date: Optional[str] = None
    notes: Optional[str] = None
    link_url: Optional[str] = None

    _status_ok = field_validator("status")(_one_of("status", TASK_STATUSES))
    _priority_ok = field_validator("priority")(_one_of("priority", TASK_PRIORITIES))


class IdeaCreate(BaseModel):
    title: str
    description: Optional[str] = None
    room_id: Optional[int] = None
    status: str = "new"
    color: str = "white"
    image_url: Optional[str] = None
    link_url: Optional[str] = None

    @field_validator("title")
    @classmethod
    def _title_not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("title is required")
        return v.strip()

    _status_ok = field_validator("status")(_one_of("status", IDEA_STATUSES))
    _color_ok = field_validator("color")(_one_of("color", IDEA_COLORS))


class SupplyCreate(BaseModel):
    name: str
    quantity: Optional[str] = None
    status: str = "needed"
    room_id: Optional[int] = None
    task_id: Optional[int] = None
    notes: Optional[str] = None
    link_url: Optional[str] = None

    @field_validator("name")
    @classmethod
    def _name_not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("name is required")
        return v.strip()

    _status_ok = field_validator("status")(_one_of("status", SUPPLY_STATUSES))


class SupplyUpdate(BaseModel):
    name: Optional[str] = None
    quantity: Optional[str] = None
    status: Optional[str] = None
    room_id: Optional[int] = None
    task_id: Optional[int] = None
    notes: Optional[str] = None
    link_url: Optional[str] = None

    _status_ok = field_validator("status")(_one_of("status", SUPPLY_STATUSES))


class IdeaUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    room_id: Optional[int] = None
    status: Optional[str] = None
    color: Optional[str] = None
    image_url: Optional[str] = None
    link_url: Optional[str] = None

    _status_ok = field_validator("status")(_one_of("status", IDEA_STATUSES))
    _color_ok = field_validator("color")(_one_of("color", IDEA_COLORS))


# ─── Rooms ───────────────────────────────────────────────────────────────────

@router.get("/rooms")
async def list_rooms(db_conn: sqlite3.Connection = Depends(get_db_conn)):
    rows = db_conn.execute(
        "SELECT * FROM renovation_rooms ORDER BY sort_order ASC, id ASC"
    ).fetchall()
    return [dict(r) for r in rows]


@router.post("/rooms", status_code=201)
async def create_room(
    body: RoomCreate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    cur = db_conn.execute(
        "INSERT INTO renovation_rooms (name, icon, notes, image_url, sort_order) VALUES (?,?,?,?,?)",
        (body.name, body.icon or "🏠", _clean(body.notes), _clean(body.image_url), body.sort_order),
    )
    db_conn.commit()
    return dict(db_conn.execute("SELECT * FROM renovation_rooms WHERE id=?", (cur.lastrowid,)).fetchone())


@router.put("/rooms/{room_id}")
async def update_room(
    room_id: int,
    body: RoomUpdate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    updates = body.model_dump(exclude_unset=True)
    if "name" in updates:
        name = (updates["name"] or "").strip()
        if not name:
            raise HTTPException(status_code=422, detail="שם החדר לא יכול להיות ריק")
        updates["name"] = name
    for field in ("notes", "image_url"):
        if field in updates:
            updates[field] = _clean(updates[field])
    existing = db_conn.execute("SELECT * FROM renovation_rooms WHERE id=?", (room_id,)).fetchone()
    if not existing:
        raise HTTPException(status_code=404, detail="החדר לא נמצא")
    if not updates:
        return dict(existing)
    set_clause = ", ".join(f"{k}=?" for k in updates)
    db_conn.execute(
        f"UPDATE renovation_rooms SET {set_clause} WHERE id=?",
        (*updates.values(), room_id),
    )
    db_conn.commit()
    return dict(db_conn.execute("SELECT * FROM renovation_rooms WHERE id=?", (room_id,)).fetchone())


@router.delete("/rooms/{room_id}", status_code=204)
async def delete_room(
    room_id: int,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    # Tasks, ideas and supplies survive the room; they simply become unassigned.
    # The ON DELETE SET NULL rule needs foreign_keys=ON, which get_connection
    # sets, but we clear them explicitly so an old connection can't orphan rows.
    db_conn.execute("UPDATE renovation_tasks SET room_id=NULL WHERE room_id=?", (room_id,))
    db_conn.execute("UPDATE renovation_ideas SET room_id=NULL WHERE room_id=?", (room_id,))
    db_conn.execute("UPDATE renovation_supplies SET room_id=NULL WHERE room_id=?", (room_id,))
    db_conn.execute("DELETE FROM renovation_rooms WHERE id=?", (room_id,))
    db_conn.commit()


# ─── Tasks ───────────────────────────────────────────────────────────────────

@router.get("/tasks")
async def list_tasks(db_conn: sqlite3.Connection = Depends(get_db_conn)):
    rows = db_conn.execute("""
        SELECT t.*, r.name AS room_name, r.icon AS room_icon
        FROM renovation_tasks t
        LEFT JOIN renovation_rooms r ON r.id = t.room_id
        ORDER BY
            CASE t.status WHEN 'in_progress' THEN 1 WHEN 'todo' THEN 2 ELSE 3 END,
            CASE t.priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
            COALESCE(t.due_date, '9999-12-31') ASC,
            t.id DESC
    """).fetchall()
    return [dict(r) for r in rows]


@router.post("/tasks", status_code=201)
async def create_task(
    body: TaskCreate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    username = _require_editor(request)
    _room_exists(db_conn, body.room_id)
    cur = db_conn.execute(
        "INSERT INTO renovation_tasks (title, room_id, status, priority, due_date, notes, link_url, created_by) "
        "VALUES (?,?,?,?,?,?,?,?)",
        (
            body.title,
            body.room_id,
            body.status,
            body.priority,
            _clean(body.due_date),
            _clean(body.notes),
            _clean(body.link_url),
            username,
        ),
    )
    db_conn.commit()
    return dict(db_conn.execute("SELECT * FROM renovation_tasks WHERE id=?", (cur.lastrowid,)).fetchone())


@router.put("/tasks/{task_id}")
async def update_task(
    task_id: int,
    body: TaskUpdate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    updates = body.model_dump(exclude_unset=True)
    if "title" in updates:
        title = (updates["title"] or "").strip()
        if not title:
            raise HTTPException(status_code=422, detail="שם המשימה לא יכול להיות ריק")
        updates["title"] = title
    for field in ("due_date", "notes", "link_url"):
        if field in updates:
            updates[field] = _clean(updates[field])
    if "room_id" in updates:
        _room_exists(db_conn, updates["room_id"])
    return _apply_updates(db_conn, "renovation_tasks", task_id, updates, "המשימה לא נמצאה")


@router.delete("/tasks/{task_id}", status_code=204)
async def delete_task(
    task_id: int,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    # Equipment outlives the task that asked for it — it stays on the shopping
    # list, just no longer tied to a task.
    db_conn.execute("UPDATE renovation_supplies SET task_id=NULL WHERE task_id=?", (task_id,))
    db_conn.execute("DELETE FROM renovation_tasks WHERE id=?", (task_id,))
    db_conn.commit()


# ─── Ideas ───────────────────────────────────────────────────────────────────

@router.get("/ideas")
async def list_ideas(db_conn: sqlite3.Connection = Depends(get_db_conn)):
    rows = db_conn.execute("""
        SELECT i.*, r.name AS room_name, r.icon AS room_icon
        FROM renovation_ideas i
        LEFT JOIN renovation_rooms r ON r.id = i.room_id
        ORDER BY i.updated_at DESC, i.id DESC
    """).fetchall()
    return [dict(r) for r in rows]


@router.post("/ideas", status_code=201)
async def create_idea(
    body: IdeaCreate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    username = _require_editor(request)
    _room_exists(db_conn, body.room_id)
    cur = db_conn.execute(
        "INSERT INTO renovation_ideas (title, description, room_id, status, color, image_url, link_url, created_by) "
        "VALUES (?,?,?,?,?,?,?,?)",
        (
            body.title,
            _clean(body.description),
            body.room_id,
            body.status,
            body.color,
            _clean(body.image_url),
            _clean(body.link_url),
            username,
        ),
    )
    db_conn.commit()
    return dict(db_conn.execute("SELECT * FROM renovation_ideas WHERE id=?", (cur.lastrowid,)).fetchone())


@router.put("/ideas/{idea_id}")
async def update_idea(
    idea_id: int,
    body: IdeaUpdate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    updates = body.model_dump(exclude_unset=True)
    if "title" in updates:
        title = (updates["title"] or "").strip()
        if not title:
            raise HTTPException(status_code=422, detail="שם הרעיון לא יכול להיות ריק")
        updates["title"] = title
    for field in ("description", "image_url", "link_url"):
        if field in updates:
            updates[field] = _clean(updates[field])
    if "room_id" in updates:
        _room_exists(db_conn, updates["room_id"])
    return _apply_updates(db_conn, "renovation_ideas", idea_id, updates, "הרעיון לא נמצא")


@router.delete("/ideas/{idea_id}", status_code=204)
async def delete_idea(
    idea_id: int,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    db_conn.execute("DELETE FROM renovation_ideas WHERE id=?", (idea_id,))
    db_conn.commit()


# ─── Supplies (ציוד) ─────────────────────────────────────────────────────────

@router.get("/supplies")
async def list_supplies(db_conn: sqlite3.Connection = Depends(get_db_conn)):
    rows = db_conn.execute("""
        SELECT s.*, r.name AS room_name, r.icon AS room_icon, t.title AS task_title
        FROM renovation_supplies s
        LEFT JOIN renovation_rooms r ON r.id = s.room_id
        LEFT JOIN renovation_tasks t ON t.id = s.task_id
        ORDER BY
            CASE s.status WHEN 'needed' THEN 1 ELSE 2 END,
            r.sort_order IS NULL, r.sort_order ASC,
            s.id DESC
    """).fetchall()
    return [dict(r) for r in rows]


@router.post("/supplies", status_code=201)
async def create_supply(
    body: SupplyCreate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    username = _require_editor(request)
    _room_exists(db_conn, body.room_id)
    _task_exists(db_conn, body.task_id)

    # An item added straight from a task inherits that task's room, so it still
    # shows up under the right room on the shopping list.
    room_id = body.room_id
    if room_id is None and body.task_id is not None:
        row = db_conn.execute(
            "SELECT room_id FROM renovation_tasks WHERE id=?", (body.task_id,)
        ).fetchone()
        if row:
            room_id = row["room_id"]

    cur = db_conn.execute(
        "INSERT INTO renovation_supplies (name, quantity, status, room_id, task_id, notes, link_url, created_by) "
        "VALUES (?,?,?,?,?,?,?,?)",
        (
            body.name,
            _clean(body.quantity),
            body.status,
            room_id,
            body.task_id,
            _clean(body.notes),
            _clean(body.link_url),
            username,
        ),
    )
    db_conn.commit()
    return dict(db_conn.execute("SELECT * FROM renovation_supplies WHERE id=?", (cur.lastrowid,)).fetchone())


@router.put("/supplies/{supply_id}")
async def update_supply(
    supply_id: int,
    body: SupplyUpdate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    updates = body.model_dump(exclude_unset=True)
    if "name" in updates:
        name = (updates["name"] or "").strip()
        if not name:
            raise HTTPException(status_code=422, detail="שם הפריט לא יכול להיות ריק")
        updates["name"] = name
    for field in ("quantity", "notes", "link_url"):
        if field in updates:
            updates[field] = _clean(updates[field])
    if "room_id" in updates:
        _room_exists(db_conn, updates["room_id"])
    if "task_id" in updates:
        _task_exists(db_conn, updates["task_id"])
    return _apply_updates(db_conn, "renovation_supplies", supply_id, updates, "הפריט לא נמצא")


@router.delete("/supplies/{supply_id}", status_code=204)
async def delete_supply(
    supply_id: int,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    db_conn.execute("DELETE FROM renovation_supplies WHERE id=?", (supply_id,))
    db_conn.commit()


# ─── Journal — before/after (יומן) ───────────────────────────────────────────

class JournalCreate(BaseModel):
    title: str
    room_id: Optional[int] = None
    entry_date: Optional[str] = None
    notes: Optional[str] = None

    @field_validator("title")
    @classmethod
    def _title_not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("title is required")
        return v.strip()


class JournalUpdate(BaseModel):
    title: Optional[str] = None
    room_id: Optional[int] = None
    entry_date: Optional[str] = None
    notes: Optional[str] = None


def _journal_entry(db_conn: sqlite3.Connection, entry_id: int) -> sqlite3.Row:
    row = db_conn.execute("SELECT * FROM renovation_journal WHERE id=?", (entry_id,)).fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="הרשומה ביומן לא נמצאה")
    return row


def _discard_photo(stored_name: Optional[str]) -> None:
    """Delete a photo file, ignoring one that is already gone.

    A failure here must never break the request that triggered it: losing the
    database row matters, a leftover file on disk does not.
    """
    if not stored_name or not _STORED_NAME_RE.match(stored_name):
        return
    try:
        (JOURNAL_PHOTOS_DIR / stored_name).unlink(missing_ok=True)
    except OSError:
        pass


@router.get("/journal")
async def list_journal(db_conn: sqlite3.Connection = Depends(get_db_conn)):
    rows = db_conn.execute("""
        SELECT j.*, r.name AS room_name, r.icon AS room_icon
        FROM renovation_journal j
        LEFT JOIN renovation_rooms r ON r.id = j.room_id
        ORDER BY COALESCE(j.entry_date, '') DESC, j.id DESC
    """).fetchall()
    return [dict(r) for r in rows]


@router.post("/journal", status_code=201)
async def create_journal_entry(
    body: JournalCreate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    username = _require_editor(request)
    _room_exists(db_conn, body.room_id)
    cur = db_conn.execute(
        "INSERT INTO renovation_journal (title, room_id, entry_date, notes, created_by) "
        "VALUES (?,?,?,?,?)",
        (body.title, body.room_id, _clean(body.entry_date), _clean(body.notes), username),
    )
    db_conn.commit()
    return dict(db_conn.execute(
        "SELECT * FROM renovation_journal WHERE id=?", (cur.lastrowid,)
    ).fetchone())


@router.put("/journal/{entry_id}")
async def update_journal_entry(
    entry_id: int,
    body: JournalUpdate,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    updates = body.model_dump(exclude_unset=True)
    if "title" in updates:
        title = (updates["title"] or "").strip()
        if not title:
            raise HTTPException(status_code=422, detail="לרשומה חייבת להיות כותרת")
        updates["title"] = title
    for field in ("entry_date", "notes"):
        if field in updates:
            updates[field] = _clean(updates[field])
    if "room_id" in updates:
        _room_exists(db_conn, updates["room_id"])
    return _apply_updates(db_conn, "renovation_journal", entry_id, updates, "הרשומה ביומן לא נמצאה")


@router.delete("/journal/{entry_id}", status_code=204)
async def delete_journal_entry(
    entry_id: int,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    row = _journal_entry(db_conn, entry_id)
    db_conn.execute("DELETE FROM renovation_journal WHERE id=?", (entry_id,))
    db_conn.commit()
    # The rows are gone, so nothing points at these files any more.
    _discard_photo(row["before_photo"])
    _discard_photo(row["after_photo"])


@router.post("/journal/{entry_id}/photo/{slot}")
async def upload_journal_photo(
    entry_id: int,
    slot: str,
    request: Request,
    file: UploadFile = File(...),
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    """Attach (or replace) the 'before' or 'after' photo of a journal entry."""
    _require_editor(request)
    column = JOURNAL_SLOTS.get(slot)
    if not column:
        raise HTTPException(status_code=400, detail="אפשר להעלות רק תמונת 'לפני' או 'אחרי'")

    row = _journal_entry(db_conn, entry_id)
    content = await file.read()
    try:
        ext, _mime = validate_image(content, file.filename, JOURNAL_MAX_PHOTO_MB)
    except UploadRejected as exc:
        raise HTTPException(status_code=400, detail=str(exc))

    stored_name = random_stored_name(ext)
    JOURNAL_PHOTOS_DIR.mkdir(parents=True, exist_ok=True)
    (JOURNAL_PHOTOS_DIR / stored_name).write_bytes(content)

    previous = row[column]
    db_conn.execute(
        f"UPDATE renovation_journal SET {column}=?, updated_at=CURRENT_TIMESTAMP WHERE id=?",
        (stored_name, entry_id),
    )
    db_conn.commit()
    # Only drop the old file once the new name is safely committed.
    _discard_photo(previous)
    return dict(db_conn.execute(
        "SELECT * FROM renovation_journal WHERE id=?", (entry_id,)
    ).fetchone())


@router.delete("/journal/{entry_id}/photo/{slot}")
async def delete_journal_photo(
    entry_id: int,
    slot: str,
    request: Request,
    db_conn: sqlite3.Connection = Depends(get_db_conn),
):
    _require_editor(request)
    column = JOURNAL_SLOTS.get(slot)
    if not column:
        raise HTTPException(status_code=400, detail="אפשר למחוק רק תמונת 'לפני' או 'אחרי'")

    row = _journal_entry(db_conn, entry_id)
    db_conn.execute(
        f"UPDATE renovation_journal SET {column}=NULL, updated_at=CURRENT_TIMESTAMP WHERE id=?",
        (entry_id,),
    )
    db_conn.commit()
    _discard_photo(row[column])
    return dict(db_conn.execute(
        "SELECT * FROM renovation_journal WHERE id=?", (entry_id,)
    ).fetchone())


@router.get("/journal-photos/{stored_name}")
async def get_journal_photo(stored_name: str):
    """Serve a journal photo.

    Its own path segment (not under /journal/{id}) so the name can never be
    read as an entry id, and the name itself is matched against the pattern
    random_stored_name() produces before it is joined onto a path.
    """
    if not _STORED_NAME_RE.match(stored_name):
        raise HTTPException(status_code=404, detail="התמונה לא נמצאה")
    path = JOURNAL_PHOTOS_DIR / stored_name
    if not path.is_file():
        raise HTTPException(status_code=404, detail="התמונה לא נמצאה")
    # Names are random and a file is never rewritten in place, so it can be
    # cached hard — on a phone that means the timeline scrolls without refetching.
    return FileResponse(path, headers={"Cache-Control": "private, max-age=31536000, immutable"})
